---
- name: Install Packages
  apt:
    name: ['aptitude', 'apt-transport-https', 'borgbackup', 'iperf', 'wget', 'curl', 'git-core', 'sudo', 'rsync', 'zip', 'unzip', 'fail2ban', 'net-tools', 'dnsutils', 'tmux', 'neovim']
    state: present
    update_cache: yes

- name: Upgrade Packages
  apt: upgrade=safe

- name: Set Timezone
  timezone:
    name: America/New_York
  ignore_errors: true

- name: Generate Locale
  locale_gen:
    name: en_US.UTF-8
    state: present

- name: Create 'wheel' Group
  group:
    name: wheel
    state: present

- name: Grant 'wheel' Sudo Privileges
  lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%wheel'
      line: '%wheel ALL=(ALL) NOPASSWD:ALL'
      validate: 'visudo -cf %s'
